# Generated by Django 5.2.7 on 2026-02-16 13:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full blog content'),
        ),
    ]
