# Generated by Django 5.2.7 on 2026-02-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='search_bg_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
