# Generated by Django 5.2.7 on 2026-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_setting_search_bg_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_text', models.TextField(verbose_name='SMS / Email / WhatsApp Text')),
                ('terms_text', models.TextField(verbose_name='Terms & Privacy Text')),
            ],
            options={
                'verbose_name': 'Consent Content',
                'verbose_name_plural': 'Consent Content',
            },
        ),
    ]
