# Generated by Django 5.2.7 on 2026-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_consentcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentcontent',
            options={'verbose_name': 'Consent Setting', 'verbose_name_plural': 'Consent Setting'},
        ),
        migrations.AlterField(
            model_name='consentcontent',
            name='sms_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consentcontent',
            name='terms_text',
            field=models.TextField(blank=True),
        ),
    ]
