# Generated by Django 5.2.7 on 2026-02-20 14:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_consentcontent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsentContent',
        ),
        migrations.AddField(
            model_name='setting',
            name='consent_sms_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='consent_terms_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
