# Generated by Django 5.2.7 on 2026-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_delete_consentcontent_setting_consent_sms_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='googletagmanager',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
